### ISSUE TITLE
能否将v2raya的配置文件移至scoop/persist下以符合规范

### ISSUE THREAD

**Issue by Chikage0o0** [v2rayA/v2raya-scoop#1]
如题

**Comment by Chikage0o0** [comment]
应该只需要新增一个环境变量就行了

**Comment by MarksonHon** [comment]
@Chikage0o0 但是这样一来，v2raya 与 v2raya-git 的数据就会被分开存储了，而不是都存储/读取在 ${env:home}\.config\v2raya 的信息，用户不一定接受这一点。可能会有“为啥我数据没了”这样的疑问

**Comment by Chikage0o0** [comment]
让v2raya-git也从persist/v2raya中取数据呢

**Comment by MarksonHon** [comment]
@Chikage0o0 也不是不行，但是scoop的规则是每一个应用都有单独的persist，像cmder与cmder-full就是两个不同的文件夹

**Comment by Chikage0o0** [comment]
@MarksonHon 其实最好还是不使用环境变量读取配置目录
是否可以这样的逻辑，程序启动时，先判断有没有config文件夹，有则数据存放在config文件夹中，没有再按照原先顺序匹配数据路径。
然后scoop这样就按照标准的程序，persist下创建配置文件夹，硬链接至current/config下，这样不会因为环境变量导致不同安装渠道配置文件的读取混乱。

**Comment by MarksonHon** [comment]
@Chikage0o0 这个判断倒是可以在安装的时候通过PowerShell脚本做，如果不存在 ~\.config\v2raya 就可以上 persist，然后加一个运行参数。
但是不清楚 scoop 的运行参数能不能写变量。
